// This file is generated by scripts/sync-monster-assets.mjs.
// Add monster images as public/monsters/<code>-<company>.png or <code> <company>.png, then run npm run prepare:monsters.

export type CompanyMonsterAsset = {
  ticker: string;
  company: string;
  file: string;
};

export const companyMonsterAssets = [
  {
    "ticker": "1332",
    "company": "ニッスイ",
    "file": "1332-ニッスイ.png"
  },
  {
    "ticker": "1605",
    "company": "INPEX",
    "file": "1605-INPEX.png"
  },
  {
    "ticker": "1721",
    "company": "コムシスホールディングス",
    "file": "1721-コムシスホールディングス.png"
  },
  {
    "ticker": "1801",
    "company": "大成建設",
    "file": "1801-大成建設.png"
  },
  {
    "ticker": "1802",
    "company": "大林組",
    "file": "1802-大林組.png"
  },
  {
    "ticker": "1803",
    "company": "清水建設",
    "file": "1803-清水建設.png"
  },
  {
    "ticker": "1808",
    "company": "長谷工コーポレーション",
    "file": "1808-長谷工コーポレーション.png"
  },
  {
    "ticker": "1812",
    "company": "鹿島建設",
    "file": "1812-鹿島建設.png"
  },
  {
    "ticker": "1925",
    "company": "大和ハウス工業",
    "file": "1925-大和ハウス工業.png"
  },
  {
    "ticker": "1928",
    "company": "積水ハウス",
    "file": "1928-積水ハウス.png"
  },
  {
    "ticker": "2002",
    "company": "日清製粉グループ本社",
    "file": "2002-日清製粉グループ本社.png"
  },
  {
    "ticker": "2269",
    "company": "明治ホールディングス",
    "file": "2269-明治ホールディングス.png"
  },
  {
    "ticker": "2282",
    "company": "日本ハム",
    "file": "2282-日本ハム.png"
  },
  {
    "ticker": "2413",
    "company": "エムスリー",
    "file": "2413-エムスリー.png"
  },
  {
    "ticker": "2432",
    "company": "ディー・エヌ・エー",
    "file": "2432-ディー・エヌ・エー.png"
  },
  {
    "ticker": "2501",
    "company": "サッポロホールディングス",
    "file": "2501-サッポロホールディングス.png"
  },
  {
    "ticker": "2502",
    "company": "アサヒグループホールディングス",
    "file": "2502-アサヒグループホールディングス.png"
  },
  {
    "ticker": "2503",
    "company": "キリンホールディングス",
    "file": "2503-キリンホールディングス.png"
  },
  {
    "ticker": "2768",
    "company": "双日",
    "file": "2768-双日.png"
  },
  {
    "ticker": "2801",
    "company": "キッコーマン",
    "file": "2801-キッコーマン.png"
  },
  {
    "ticker": "2802",
    "company": "味の素",
    "file": "2802-味の素.png"
  },
  {
    "ticker": "285A",
    "company": "キオクシアホールディングス",
    "file": "285A-キオクシアホールディングス.png"
  },
  {
    "ticker": "2871",
    "company": "ニチレイ",
    "file": "2871-ニチレイ.png"
  },
  {
    "ticker": "2914",
    "company": "日本たばこ産業",
    "file": "2914-日本たばこ産業.png"
  },
  {
    "ticker": "3086",
    "company": "J.フロント リテイリング",
    "file": "3086-J.フロント リテイリング.png"
  },
  {
    "ticker": "3092",
    "company": "ZOZO",
    "file": "3092-ZOZO.png"
  },
  {
    "ticker": "3099",
    "company": "三越伊勢丹ホールディングス",
    "file": "3099-三越伊勢丹ホールディングス.png"
  },
  {
    "ticker": "3289",
    "company": "東急不動産ホールディングス",
    "file": "3289-東急不動産ホールディングス.png"
  },
  {
    "ticker": "3382",
    "company": "セブン＆アイ・ホールディングス",
    "file": "3382-セブン＆アイ・ホールディングス.png"
  },
  {
    "ticker": "3401",
    "company": "帝人",
    "file": "3401-帝人.png"
  },
  {
    "ticker": "3402",
    "company": "東レ",
    "file": "3402-東レ.png"
  },
  {
    "ticker": "3405",
    "company": "クラレ",
    "file": "3405-クラレ.png"
  },
  {
    "ticker": "3407",
    "company": "旭化成",
    "file": "3407-旭化成.png"
  },
  {
    "ticker": "3436",
    "company": "SUMCO",
    "file": "3436-SUMCO.png"
  },
  {
    "ticker": "3659",
    "company": "ネクソン",
    "file": "3659-ネクソン.png"
  },
  {
    "ticker": "3697",
    "company": "SHIFT",
    "file": "3697-SHIFT.png"
  },
  {
    "ticker": "3861",
    "company": "王子ホールディングス",
    "file": "3861-王子ホールディングス.png"
  },
  {
    "ticker": "4004",
    "company": "レゾナック・ホールディングス",
    "file": "4004-レゾナック・ホールディングス.png"
  },
  {
    "ticker": "4005",
    "company": "住友化学",
    "file": "4005-住友化学.png"
  },
  {
    "ticker": "4021",
    "company": "日産化学",
    "file": "4021-日産化学.png"
  },
  {
    "ticker": "4042",
    "company": "東ソー",
    "file": "4042-東ソー.png"
  },
  {
    "ticker": "4043",
    "company": "トクヤマ",
    "file": "4043-トクヤマ.png"
  },
  {
    "ticker": "4061",
    "company": "デンカ",
    "file": "4061-デンカ.png"
  },
  {
    "ticker": "4063",
    "company": "信越化学工業",
    "file": "4063-信越化学工業.png"
  },
  {
    "ticker": "4183",
    "company": "三井化学",
    "file": "4183-三井化学.png"
  },
  {
    "ticker": "4188",
    "company": "三菱ケミカルグループ",
    "file": "4188-三菱ケミカルグループ.png"
  },
  {
    "ticker": "4208",
    "company": "UBE",
    "file": "4208-UBE.png"
  },
  {
    "ticker": "4452",
    "company": "花王",
    "file": "4452-花王.png"
  },
  {
    "ticker": "4901",
    "company": "富士フイルム",
    "file": "4901-富士フイルム.png"
  },
  {
    "ticker": "4911",
    "company": "資生堂",
    "file": "4911-資生堂.png"
  },
  {
    "ticker": "5019",
    "company": "出光興産",
    "file": "5019-出光興産.png"
  },
  {
    "ticker": "5020",
    "company": "ENEOS",
    "file": "5020-ENEOS.png"
  },
  {
    "ticker": "5101",
    "company": "横浜ゴム",
    "file": "5101-横浜ゴム.png"
  },
  {
    "ticker": "5108",
    "company": "ブリヂストン",
    "file": "5108-ブリヂストン.png"
  },
  {
    "ticker": "5201",
    "company": "AGC",
    "file": "5201-AGC.png"
  },
  {
    "ticker": "5214",
    "company": "日本電気硝子",
    "file": "5214-日本電気硝子.png"
  },
  {
    "ticker": "5233",
    "company": "太平洋セメント",
    "file": "5233-太平洋セメント.png"
  },
  {
    "ticker": "5301",
    "company": "東海カーボン",
    "file": "5301-東海カーボン.png"
  },
  {
    "ticker": "5332",
    "company": "TOTO",
    "file": "5332-TOTO.png"
  },
  {
    "ticker": "5333",
    "company": "日本碍子（NGK）",
    "file": "5333-日本碍子（NGK）.png"
  },
  {
    "ticker": "6988",
    "company": "日東電工",
    "file": "6988-日東電工.png"
  }
] satisfies CompanyMonsterAsset[];

export const companyMonsterAssetDiagnostics = {
  "totalFiles": 90,
  "usableFiles": 61,
  "ignoredFiles": [
    ".DS_Store",
    "bank-golem-icon-transparent.png",
    "bank-golem-icon.png",
    "bank-golem-transparent.png",
    "bank-golem.png",
    "chip-thunder-icon-transparent.png",
    "chip-thunder-icon.png",
    "chip-thunder-transparent.png",
    "chip-thunder.png",
    "grid-wyvern-icon-transparent.png",
    "grid-wyvern-icon.png",
    "grid-wyvern-transparent.png",
    "grid-wyvern.png",
    "medica-seraph-icon-transparent.png",
    "medica-seraph-icon.png",
    "medica-seraph-transparent.png",
    "medica-seraph.png",
    "nintendora-icon-transparent.png",
    "nintendora-icon.png",
    "nintendora-transparent.png",
    "nintendora.png",
    "sonic-leo-icon-transparent.png",
    "sonic-leo-icon.png",
    "sonic-leo-transparent.png",
    "sonic-leo.png",
    "toyodora-icon-transparent.png",
    "toyodora-icon.png",
    "toyodora-transparent.png",
    "toyodora.png"
  ],
  "duplicateTickers": []
} as const;
